// <auto-generated />
using MVCDemo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MVCDemo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200820095716_SeedingEmployeeData")]
    partial class SeedingEmployeeData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MVCDemo.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AvatarPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarPath = "~/images/captian.png",
                            Department = 0,
                            Email = "nhanvu@gmail.com",
                            FullName = "Captain America"
                        },
                        new
                        {
                            Id = 2,
                            AvatarPath = "~/images/hulk.png",
                            Department = 1,
                            Email = "tramphan@gmail.com",
                            FullName = "Hulk"
                        },
                        new
                        {
                            Id = 3,
                            AvatarPath = "~/images/ironmanchibi.jpg",
                            Department = 0,
                            Email = "nhungnguyen@gmail.com",
                            FullName = "Iron Man"
                        },
                        new
                        {
                            Id = 4,
                            AvatarPath = "~/images/spidermanchibi.jpg",
                            Department = 1,
                            Email = "quanvu@gmail.com",
                            FullName = "Spider Man"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
